# common/argo/base/workflow-controller/workflow-controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
  namespace: onepanel
spec:
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      containers:
      - args:
        - --configmap
        - workflow-controller-configmap
        - --executor-image
        - argoproj/argoexec:v2.9.4
        command:
        - workflow-controller
        image: argoproj/workflow-controller:v2.9.4
        name: workflow-controller
      serviceAccountName: argo
