apiVersion: v1
kind: Secret
metadata:
  name: artifact-repository-gcs-credentials
  namespace: $(applicationDefaultNamespace)
type: Opaque
# These values will be replaced by the CLI, not Kustomize
data:
  credentials.json: $(artifactRepositoryServiceAccountKey)