apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - role.yaml
  - rolebinding.yaml
  - serviceaccount.yaml