# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Component: Workflow engine configuration
# Description: Configuration options for the Workflow engine
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
workflowEngine:
  # The executor workflow engine uses to perform certain actions like monitoring pod logs, collecting artifacts, managing container lifecycles, etc.
  # The possible values are `docker` and `pns`:
  # - `docker` is more reliable, however it mounts the `docker.sock` of the host makes it less secure.
  # - `pns` is more secure, however in some versions of Kubernetes, it tends to fail on tasks that take less than 15 seconds.
  containerRuntimeExecutor:
    required: true
    default: pns