apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- istio.yaml
- gateway.yaml
transformers:
- metadataLabelTransformer.yaml
patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: istio-ingressgateway
      namespace: istio-system
    path: deployment-ingressgateway-patch.yaml

